package HelloApll;


/**
* HelloApll/HelloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Dhruvi/eclipse-workspace/Assignment2/src/Hello.idl
* Thursday, June 13, 2019 8:03:53 PM EDT
*/

abstract public class HelloHelper
{
  private static String  _id = "IDL:HelloApll/Hello:1.0";

  public static void insert (org.omg.CORBA.Any a, HelloApll.Hello that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HelloApll.Hello extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HelloApll.HelloHelper.id (), "Hello");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HelloApll.Hello read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HelloStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HelloApll.Hello value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HelloApll.Hello narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HelloApll.Hello)
      return (HelloApll.Hello)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HelloApll._HelloStub stub = new HelloApll._HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HelloApll.Hello unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HelloApll.Hello)
      return (HelloApll.Hello)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HelloApll._HelloStub stub = new HelloApll._HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
