package HelloApll;


/**
* HelloApll/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Dhruvi/eclipse-workspace/Assignment2/src/Hello.idl
* Thursday, June 13, 2019 8:03:53 PM EDT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
