package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Concordia/COMP6231/CORBA_labDemo/src/Addition.idl
* Tuesday, June 11, 2019 9:39:26 PM EDT
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
